-- phpMyAdmin SQL Dump
-- version 4.0.0-beta1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 30, 2013 at 03:09 PM
-- Server version: 5.1.56-log
-- PHP Version: 5.3.15-pl0-gentoo

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `wstat2`
--

-- --------------------------------------------------------

--
-- Table structure for table `cat_achiev_details`
--

CREATE TABLE IF NOT EXISTS `cat_achiev_details` (
  `id` int(11) NOT NULL,
  `name` varchar(128) NOT NULL,
  `type` varchar(10) NOT NULL,
  `needLabel` tinyint(1) NOT NULL DEFAULT '0',
  `title_en` varchar(128) NOT NULL,
  `title_ru` varchar(128) NOT NULL,
  `title_ko` varchar(128) NOT NULL,
  `description_en` text NOT NULL,
  `description_ru` text NOT NULL,
  `description_ko` text NOT NULL,
  `icon` varchar(128) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE KEY `id` (`id`),
  KEY `type` (`type`),
  KEY `icon` (`icon`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cat_achiev_details`
--

INSERT INTO `cat_achiev_details` (`id`, `name`, `type`, `needLabel`, `title_en`, `title_ru`, `title_ko`, `description_en`, `description_ru`, `description_ko`, `icon`) VALUES
(730, 'medalCarius', 'MAJOR', 0, 'Carius'' Medal', 'Медаль Кариуса', '카리우스 훈장', 'Awarded for the destruction of enemy tanks and self-propelled guns in four classes.', 'Выдаётся в одной из четырёх степеней за уничтожение вражеских танков и САУ.', '적 전차나 자주포를 격파한 수에 따라 4단계의 명예 훈장 수여.', 'medal_carius'),
(210, 'medalHalonen', 'EPIC', 1, 'Halonen''s Medal', 'Медаль Халонена', '할로넨 훈장', 'Awarded for destroying three or more enemy tanks or tank destroyers with a tank destroyer.\nThe targets must be at least two tiers higher than the player''s vehicle.\nUnavailable in Clan Wars.\n\nErkki Halonen, a sergeant in the Finnish Army and a tank ace, destroyed three T-34, two KV-1, and two ISU-152 with his StuG III in battles during June and July 1944.', 'Награждается игрок, в ходе боя уничтоживший на ПТ-САУ 3 и более танков или ПТ-САУ противника.\nВ зачёт идут цели, превосходящие танк игрока не менее, чем на 2 уровня.\nНе выдаётся в клановых войнах.\n\nЭркки Халонен — танковый ас, сержант финской армии. В ходе боёв в июне — июле 1944 г. на StuG III уничтожил три Т-34, два КВ-1 и два ИСУ-152.', '구축전차로 3대 이상의 적 전차나 구축전차 격파 시 수여.\n적 전차의 등급은 플레이어의 전차보다 최소 2등급 이상 높아야 한다.\n클랜전에서는 수여되지 않는다.\n\n에르끼 할로넨은 핀란드의 부사관이며 전차 에이스로, 1944년 6월과 7월 사이에 Stug III로 T-34 3대, KV-1 2대, ISU-152 2대를 격파하였다.', 'medal_halonen'),
(30, 'invader', 'BATTLE', 1, 'Invader', '«Захватчик»', '침략자', '• Capture the maximum number of points from the enemy base (not less than 80).\n	• The achievement is granted on successful base capture, including only the points that were part of the base capture.\n	• If two or more players have gained an equal amount of capture points, the achievement is granted to the player who has earned more XP in the battle (including additional XP provided to Premium Account users).\n	• If the amount of XP is equal as well, the achievement is not awarded.', '• Присуждается игроку, получившему наибольшее количество очков захвата базы, но не менее 80.\n	• Выдаётся после состоявшегося захвата.\n	• В зачёт идут только очки, обеспечившие захват.\n	• Присваивается получившему наибольшее количество опыта.', '• 적 기지 점령 수치를 80% 이상 축적한 점령자 중에서 가장 높은 수치를 기록하면 획득.\n	• 적 기지 점령 수치만 계산에 포함되며, 성공적으로 적 기지를 점령하였을 때 업적을 획득한다.\n	• 2명 이상의 감소 수치가 동일할 경우 해당 전투에서 더 많은 경험치를 획득한 자(프리미엄 계정 경험치 포함)가 획득한다.\n	• 만일 획득 경험치도 동일한 경우에는 아무도 해당 업적을 획득할 수 없다.', 'invader'),
(220, 'medalFadin', 'EPIC', 1, 'Fadin''s Medal', 'Медаль Фадина', '파딘 훈장', 'Awarded for destroying the last enemy vehicle in the battle with the last shell in the ammo.\nUnavailable in Clan Wars.\n\nA Hero of the Soviet Union, Alexander Fadin was a T-34 commander. Supported by one infantry platoon, Fadin managed to capture Dashukovka village and hold it for five hours with one tank, and destroyed three tanks, one half-track, two mortars, and 12 machinegun nests. His crew also shot down an enemy plane with his tank''s coaxial machinegun.', 'Награждается игрок, уничтоживший последним снарядом в боекомплекте последнюю вражескую машину.\nНе выдаётся в клановых войнах.\n\nАлександр Михайлович Фадин — командир Т-34. Одним танком, при поддержке взвода пехоты, захватил и удерживал с. Дашуковка в течение пяти часов, уничтожив при этом три танка, один бронетранспортёр, два миномёта, двенадцать пулемётных точек. Также сумел сбить самолёт противника выстрелом из орудия.', '자신의 전차에 남은 마지막 1발의 포탄으로 적의 마지막 전차 격파 시 수여.\n클랜전에서는 수여되지 않는다.\n\n알렉산드르 파딘은 소련 연방 영웅 칭호를 수여받은 T-34 전차의 전차장이었다. 파딘은 보병 1개 소대의 지원만으로 다슈코프카 마을을 점령한 뒤 5시간의 방어전 중 적 전차 3대, 반궤도 장갑차 1대, 박격포 2문, 12개소의 기관총 진지를 격파했다. 파딘의 전차는 심지어 대공기관총으로 적 항공기 한 대를 격추시키기도 했다.', 'medal_fadin'),
(720, 'medalEkins', 'MAJOR', 0, 'Ekins'' Medal', 'Медаль Экинса', '에킨스 훈장', 'Awarded in four classes for destroying tier 8, 9, or 10 enemy tanks and self-propelled guns.', 'Выдаётся в одной из четырёх степеней за уничтожение вражеских танков и САУ 8-го, 9-го или 10-го уровня.', '8단계 이상의 적 전차와 자주포를 격파한 수에 따라 4단계의 명예 훈장 수여.', 'medal_ekins'),
(490, 'mousebane', 'SPECIAL', 1, 'Mouse Trap', '«Гроза Мышей»', '쥐사냥꾼', '• Destroy 10 or more PzKpfw VIII Maus tanks.\n	• Total results on all tanks are included.', '• Присуждается игроку, уничтожившему 10 и более PzKpfw VIII Maus.\n	• В зачёт идёт сумма результатов по всем танкам.', '• PzKpfw VIII Maus를 10대 이상 격파한 자에게 수여.\n	• 보유한 전차들의 총합으로 계산.', 'mousebane'),
(780, 'medalKay', 'MAJOR', 0, 'Kay''s Medal', 'Медаль Кея', '케이 훈장', 'Awarded for achieving the Battle Hero status in four classes.', 'Выдаётся в одной из четырёх степеней за получение статуса «Герой Битвы».', '훈장 획득 수에 따라 4단계의 명예 훈장 수여.', 'medal_kay'),
(20, 'defender', 'BATTLE', 1, 'Defender', '«Защитник»', '수비수', '• Reduce the number of enemy capture points of a friendly base by 70 or more.\n	• If two or more players have reduced an equal amount of capture points, the achievement is granted to the player who has earned more XP in the battle (including additional XP provided to Premium Account users).', '• Присуждается игроку, сбившему наибольшее количество очков захвата своей базы, но не менее 70.\n	• При равном количестве сбитых очков награда присуждается тому, кто в данном бою заработал наибольшее количество очков опыта с учётом премиум аккаунта.', '• 적의 아군기지 점령 수치를 70% 이상 감소시켰을 때 획득.\n	• 2명 이상의 감소 수치가 동일할 경우 해당 전투에서 더 많은 경험치를 획득한 자(프리미엄 경험치 포함)가 해당 업적을 획득한다.', 'defender'),
(760, 'medalLeClerc', 'MAJOR', 0, 'Leclerc''s Medal', 'Медаль Леклерка', '르클레르 훈장', 'Awarded for the total amount of the player''s enemy base capture points. An unsuccessful or reduced capture does not count toward this number.', 'Выдаётся за суммарное количество очков захвата базы. Неуспешный и сбитый захват в зачёт не идёт.', '플레이어의 적 기지 총 점령 점수에 따라 수여. 점령으로 승리하지 못하거나, 적에게 감소 당한 점령 점수는 해당하지 않는다.', 'medal_le_clerc'),
(60, 'supporter', 'BATTLE', 1, 'Confederate', '«Поддержка»', '연맹', '• Hit more enemy vehicles (at least 6) than any other player on your team. These enemy vehicles must subsequently be destroyed by another player or self-destroy.\n	• If two or more players score an equal amount of hits, the achievement is granted to the player who earned more XP in the battle, including additional XP provided to Premium Account users.', '• Присуждается игроку, который произвёл наибольшее количество попаданий (не менее 6) по различным противникам, которые впоследствии были уничтожены другими игроками или самоуничтожились.\n	• При равном количестве попаданий выдаётся игроку, получившему больше очков опыта за бой с учётом премиум аккаунта.', '• 팀 내에서 여러 대의 적 전차(최소 6대)를 가장 많이 명중시킨 자에게 수여. 해당 적 전차는 다른 플레이어에게 파괴되거나 자살해야만 한다.\n	• 2명 이상의 기록이 동일할 경우 해당 전투에서 더 많은 경험치를 획득한 자(프리미엄 경험치 포함)가 획득한다.', 'supporter'),
(40, 'steelwall', 'BATTLE', 1, 'Steel Wall', '«Стальная cтена»', '철벽', '• Receive more potential damage than any player on your team, at least 1,000 HP, and survive.\n	• Receive at least 11 hits.\n	• If two or more players receive equal amount of potential damage, the achievement is granted to the player who received the greatest amount of hits.\n	• If two or more players receive equal amount of potential damage and equal number of hits, the achievement is granted to the player who earned more XP for the battle, including additional XP provided to Premium Account users.', '• Присуждается игроку, получившему наибольший потенциальный урон, но не менее 1 000 единиц.\n	• Необходимо получить не менее 11 попаданий.\n	• Присуждается только выжившим.\n	• При равном количестве полученного потенциального урона выдаётся игроку, получившему больше попаданий.\n	• При равном количестве полученного потенциального урона и попаданий, присуждается игроку, набравшему больше очков опыта за бой с учетом премиум аккаунта.', '• 팀 내에서 가장 많이 적에게 피격 당하고(최저 11발), 받은 피해량이 1,000 이상인 상태에서 살아남은 자에게 수여.\n	• 2명 이상의 피격 횟수가 동일할 경우 해당 전투에서 받은 피해량이 제일 많은 자가 획득한다.\n	• 2명 이상이 피격량도 동일할 경우 해당 전투에서 더 많은 경험치를 획득한 자(프리미엄 경험치 포함)가 획득한다.', 'steelwall'),
(710, 'medalAbrams', 'MAJOR', 0, 'Abrams'' Medal', 'Медаль Абрамса', '에이브럼스 훈장', 'Awarded in one of four classes for the total number of team victories in which the player survived the battle.', 'Выдаётся за суммарное количество побед, одержанных командой, в которых игрок остался жив.', '플레이어가 생존한 상태에서 승리한 전투 수에 따라 4단계의 명예 훈장 수여.', 'medal_abrams'),
(750, 'medalPoppel', 'MAJOR', 0, 'Popel''s Medal', 'Медаль Попеля', '포펠 훈장', 'Awarded for detecting enemy tanks and self-propelled guns in all battles, in four classes.', 'Выдаётся в одной из четырёх степеней за обнаружение вражеских танков и САУ по итогам всех проведённых боев.', '전투 중에 발견한 적 전차와 자주포의 수에 따라 총 4단계의 명예 훈장 수여.', 'medal_poppel'),
(180, 'medalOrlik', 'EPIC', 1, 'Orlik''s Medal', 'Медаль Орлика', '오를리크 훈장', 'Awarded for destroying three or more enemy tanks or tank destroyers with a light tank. The targets must be at least two tiers higher than the player''s tank.\nUnavailable in Clan Wars.\n\nRoman Edmund Orlik, a Polish Army sergeant, was a tank ace who knocked out 13 German tanks with his light TKS tankette in September 1939.', 'Награждается игрок, в ходе боя уничтоживший на лёгком танке 3 и более танка или ПТ-САУ противника. В зачёт идут цели, превосходящие танк игрока не менее, чем на 2 уровня.\nНе выдаётся в клановых войнах.\n\nРоман Эдмунд Орлик — танковый ас, сержант польской армии. За сентябрь 1939 г., сражаясь на танкетке TKS, подбил тринадцать немецких танков.', '경전차로 3대 이상의 적 전차 혹은 구축전차를 격파 시 수여. 적 전차의 단계은 플레이어의 전차보다 최소 2단계 이상 높아야 한다.\n클랜전에서는 수여되지 않는다.\n\n폴란드 육군 부사관 로만 에드문트 오를리크는 1939년 9월 TKS 초경전차로 13대의 독일 전차를 격파한 전차 에이스였다.', 'medal_orlik'),
(560, 'handOfDeath', 'SPECIAL', 1, 'Reaper', '«Коса Смерти»', '사신', '• Destroy 3 or more enemy vehicles in a row with a single shell each.\n	• This achievement is granted on completion of the series.\n	• An unbroken series continues in the next battle using the current vehicle.\n	• Every vehicle has its own series. Only the longest series is included.', '• Присуждается игроку, уничтожившему подряд 3 и более машины противника, затратив только по одному снаряду на каждую.\n	• Если серия не прервалась, то в зачёт пойдут также результаты следующего боя на этой же машине.\n	• Серия ведётся для каждой машины отдельно. В общий зачёт идёт максимальная серия.\n	• Достижение выдаётся в момент окончания серии.', '• 전투에서 3대 이상의 적 전차를 일격에 격파한 경우 획득.\n	• 연속 기록이 끊길 경우 수여.\n	• 연속으로 기록이 이어질 경우, 동일 전차를 이용한 다음 전투에도 해당 기록이 계속된다.\n	• 모든 전차는 각기 기록을 가지며, 가장 높은 횟수만 기록된다.', 'hand_of_death'),
(50, 'sniper', 'BATTLE', 1, 'Sniper', '«Снайпер»', '저격수', '• Achieve at least 85% hits out of a minimum of 10 shots fired with the potential damage of 1,000 HP or more.\n	• Direct hits on friendly vehicles are not allowed.\n	• Non-penetrating hits are included.\n	• If two or more players have equal hit ratio, the achievement is granted to the player with the highest number of hits.\n	• If two or more players have equal hit ratio and equal number of hits, the achievement is granted to the player who earned more XP for the battle, including additional XP provided to Premium Account users.', '• Присуждается игроку, который, не задевая союзников прямыми выстрелами, произвёл не менее 85% попаданий по противнику, сделав не менее 10-ти выстрелов с потенциальным уроном от 1 000 единиц.\n	• Непробитие засчитывается.\n	• При равном проценте попаданий присуждается игроку, нанёсшему больше попаданий.\n	• При равном проценте и количестве попаданий присуждается игроку, набравшему больше очков опыта за бой с учётом премиум аккаунта.', '• 최소 10발을 발사하여 85% 이상 명중을 기록하고 명중한 포탄의 총 공격력이 1,000 이상일 경우 수여.\n	• 아군을 공격한 경우는 포함되지 않으며, 적 전차에 명중됐으나 관통하지 못했을 때도 총 공격력에 포함된다.\n	• 명중률이 동일할 경우 명중 횟수가 가장 높은 플레이어가 획득한다.\n	• 2명 이상의 명중률이 동일할 경우 가장 높은 피해를 준 자가 획득한다.\n	• 피해양도 동일할 경우 해당 전투에서 더 많은 경험치를 획득한 자(프리미엄 경험치 포함)가 획득한다.', 'sniper'),
(10, 'warrior', 'BATTLE', 1, 'Top Gun', '«Воин»', '탑건', '• Destroy more enemy vehicles (at least 6) than any other player.\n	• If two or more players have destroyed an equal amount of vehicles, the achievement is granted to the player who earned more XP for the battle.', '• Присуждается игроку, уничтожившему наибольшее количество машин противника (не менее 6).\n	• При равном счёте присуждается игроку, получившему наибольшее количество очков опыта за бой.', '• 팀에서 적 전차를 가장 많이(최소 6대) 격파한 자에게 수여.\n	• 2명 이상의 기록이 동일할 경우 해당 전투에서 더 많은 경험치를 획득한 자(프리미엄 경험치 포함)가 획득한다.', 'warrior'),
(470, 'titleSniper', 'SPECIAL', 1, 'Sharpshooter', '«Стрелок»', '명사수', '• Hit an enemy vehicle 10 or more times in a row without missing.\n	• The results of the next battle using the same vehicle continue to count towards this number, until the sequence is broken by a miss.\n	• Every vehicle has its own series. Only the longest series is included.', '• Присуждается игроку, который попал по вражеской технике 10 и более раз подряд.\n	• Если серия попаданий не прервалась промахом, то в зачёт пойдут также результаты следующего боя на этой же машине.\n	• Серия ведётся для каждой машины отдельно. В общий зачёт идёт максимальная серия.', '• 적 전차에 최소 10발 이상의 공격을 빗나가는 일이 없이 명중시켰을 시 수여.\n	• 동일 전차를 사용한 다음 전투에도 해당 기록이 계속 집계되지만, 한 번이라도 명중에 실패하면 초기화된다.\n	• 모든 전차는 각기 기록을 가지며, 가장 높은 횟수만 기록된다.', 'title_sniper'),
(170, 'medalBoelter', 'EPIC', 1, 'Bölter''s Medal', 'Медаль Бёльтера', '뵐터 훈장', 'Awarded for destroying 7 or more enemy tanks and self-propelled guns with a tank or tank destroyer, or 10 or more vehicles with a self-propelled gun in one battle. The targets must be at least tier four enemy vehicles.\nNo longer available.\n\nJohannes Bölter was one of the most successful German tank aces of WWII. He participated in operations in the invasions of Poland, France, Greece, and the Soviet Union, as well as in the defense of France.', 'Награждается игрок, уничтоживший в одном бою 7 и более вражеских танков и САУ на танке или ПТ-САУ либо 10 и более на САУ. В зачёт идут цели 4-го уровня и выше.\nМедаль не выдаётся.\n\nГанс Бёльтер — один из наиболее успешных немецких танковых асов Второй мировой войны. Участвовал в боевых действиях в Польше, Франции, Греции, на территории СССР и в Нормандии.', '한 전투에서 전차 또는 구축전차로 전차나 자주포를 7대 이상 격파하거나 자주포로 전차나 자주포를 10대 이상 격파한 자에게 수여. 격파한 적 전차 모두 4단계 이상이어야 한다.\n클랜전에서는 수여되지 않는다.\n\n요하네스 뵐터는 제2차 세계대전 당시 독일군의 가장 우수한 전차 에이스 중 한 명으로, 폴란드, 프랑스, 그리스, 소련 침공 작전 및 프랑스 방어전에 참전하였다.', 'medal_boelter'),
(230, 'medalBurda', 'EPIC', 1, 'Burda''s Medal', 'Медаль Бурды', '부르다 훈장', 'Awarded to players who destroy 5 or more enemy self-propelled guns with a tank or Tank Destroyer.\nUnavailable in Clan Wars.\n\nGuards Colonel Alexander Burda was a Soviet tank ace and a Hero of the Soviet Union. On October 4th, 1941, Burda organized an ambush that destroyed an enemy armored column, including 10 medium and light tanks, two trucks with antitank guns, and five infantry vehicles.', 'Награждается игрок, уничтоживший на танке или ПТ-САУ в одном бою 5 или более САУ противника.\nНе выдаётся в клановых войнах.\n\nАлександр Фёдорович Бурда — советский танковый ас, Герой Советского Союза, гвардии подполковник. 4 октября 1941 г. организовал засаду, в результате которой была разгромлена колонна противника, в том числе десять средних и лёгких танков, два тягача с ПТ-орудиями, пять автомашин с пехотой.', '전차나 구축전차로 적 자주포를 5대 이상 격파 시 수여.\n클랜전에서는 수여되지 않는다.\n\n근위중령 알렉산드르 부르다는 소비에트 연방 영웅 칭호를 수여받은 소련의 전차 에이스였다. 그는 1941년 10월 4일 KV-2 전차로 적 기갑부대에 매복공격을 가하여 10대의 경전차와 중형(中)전차, 2대의 대전차포 견인 트럭, 5대의 병력 수송 차량을 격파하였다.', 'medal_burda'),
(65, 'scout', 'BATTLE', 1, 'Scout', '«Разведчик»', '정찰병', 'Detect most enemy tanks and self-propelled guns than anyone else on your team (at least nine). The achievement is granted to the winning team only. If two or more players have detected equal number of enemy vehicles, the achievement is granted to the player who has earned more XP, including additional XP provided to Premium account users. If the amount of XP is equal as well, the achievement is not granted.', 'Присваивается игроку, обнаружившему наибольшее количество танков и САУ противника (9 и более). Если по итогам боя двое или более игроков лидируют по этому показателю при одинаковом количестве обнаруженных единиц техники, то звание присваивается игроку, получившему за бой большее количество очков опыта с учетом наличия/отсутствия премиум-аккаунта. При равном опыте за бой - не выдается никому. Выдаётся при условии, что команда победила.', '팀 내에서 가장 많은 적 전차나 자주포를 발견했을 시 수여. (최소 9대) 자신의 팀이 승리했을 때 수여.', 'scout'),
(450, 'beasthunter', 'SPECIAL', 1, 'Hunter', '«Зверобой»', '사냥꾼', 'Destroy 100 or more:\n	• Jagdpanther\n	• Jagdtiger\n	• PzKpfw V Panther\n	• Panther II\n	• PzKpfw VI Tiger\n	• PzKpfw VI Tiger (P)\n	• PzKpfw VI Ausf. B Tiger II\n	• Löwe\n	• GW Panther\n	• GW Tiger\n	• Jagdpanther II\n	• 8.8 cm Pak43 JagdTiger\n	• Panther-M10', 'Присуждается игроку, уничтожившему 100 или более:\n	• Jagdpanther\n	• Jagdtiger\n	• PzKpfw V Panther\n	• Panther II\n	• PzKpfw VI Tiger\n	• PzKpfw VI Tiger (P)\n	• PzKpfw VI Ausf. B Tiger II\n	• Löwe\n	• GW Panther\n	• GW Tiger\n	• Jagdpanther II\n	• 8.8 cm Pak43 JagdTiger\n	• Panther-M10', '아래의 전차들을 100대 이상 격파 시 수여:\n	• Jagdpanther\n	• Jagdtiger\n	• PzKpfw V Panther\n	• Panther II\n	• PzKpfw VI Tiger\n	• PzKpfw VI Tiger (P)\n	• PzKpfw VI Ausf. B Tiger II\n	• Löwe\n	• GW Panther\n	• GW Tiger\n	• Jagdpanther II\n	• 8.8 cm Pak43 JagdTiger', 'beasthunter'),
(550, 'kamikaze', 'SPECIAL', 1, 'Kamikaze', '«Камикадзе»', '카미카제', 'Destroy a higher tier enemy vehicle by ramming it. The achievement is granted only once in the course of the battle.', 'Присуждается игроку, уничтожившему тараном танк более высокого уровня. Выдаётся не более одного достижения за бой.', '자신보다 상위 단계의 전차를 충돌하여 격파 시 획득. 해당 업적은 한 전투에 한 번만 획득할 수 있다.', 'kamikaze'),
(480, 'raider', 'SPECIAL', 1, 'Raider', '«Рейдер»', '침입자', '• Capture the enemy base and remain undetected during the entire battle.\n	• The achievement is granted even if the vehicle was accidentally hit or damaged.', '• Присуждается игроку, который захватил базу и в ходе боя ни разу не был обнаружен противником.\n	• Случайные попадания и повреждения танка не являются препятствием.', '• 적에게 발견되지 않고 전투가 끝날 때까지 단독으로 적 기지를 점령한 자에게 수여.\n	• 발견되지 않은 상태라면 적의 공격에 피탄되거나 전차가 피해를 입었더라도 수여된다.', 'raider'),
(190, 'medalOskin', 'EPIC', 1, 'Oskin''s Medal', 'Медаль Оськина', '오스킨 훈장', 'Awarded to players on medium tanks who destroy 3 enemy tanks or tank destroyers. The targets must be at least 2 tiers higher than the player''s tank.\nUnavailable in Clan Wars.\n\nAlexander Oskin, a Hero of the Soviet Union, was a tank commander who destroyed three King Tigers with his T-34 during a reconnaissance operation near Oglenduv on August 11th, 1944.', 'Награждается игрок, в ходе боя на среднем танке уничтоживший 3 танка или ПТ-САУ противника. В зачёт идут цели, превосходящие танк игрока не менее, чем на 2 уровня.\nНе выдаётся в клановых войнах.\n\nАлександр Петрович Оськин — командир танка, Герой Советского Союза. 11 августа 1944 г., находясь в разведке у Оглендува, уничтожил три «Королевских тигра» на Т-34.', '중(中)형전차로 한 전투 중 3대 이상의 적 격파시 수여. 적 전차는 플레이어의 전차보다 최소 2단계 이상 높아야 한다.\n클랜전에서는 수여되지 않는다.\n\n소련 영웅인 알렉산드르 오스킨은 T-34의 전차장으로, 1944년 8월 19일 오글렌두프 근교의 정찰 임무 중 자신의 T-34로 독일군 King Tiger 3대를 격파했다.', 'medal_oskin'),
(240, 'medalBillotte', 'EPIC', 1, 'Billotte''s Medal', 'Медаль Бийота', '비요트 훈장', 'Awarded to players who destroy at least 2 enemy vehicles and survive the battle to victory despite receiving at least 5 different critical hits and losing 80% or more of their hit points.\nDestroyed enemy vehicles count after all damage is received.\nUnavailable in Clan Wars.\n\nPierre Billotte was a captain in the French Army who destroyed 2 PzKpfw IV, 11 PzKpfw III and two guns with his Char B1 bis on May 16th, 1940.', 'Награждается игрок, уничтоживший не менее 2-х машин противника в победном бою.\nДля получения награды необходимо выжить, несмотря на получение 5-ти разных критических повреждений и потерю 80% прочности танка.\nУчёт уничтоженных противников начинается после получения всех перечисленных повреждений.\nНе выдаётся в клановых войнах.\n\nПьер Бийот — капитан французской армии, в ходе боя 16 мая 1940 г. уничтоживший на B1 bis два PzKpfw IV, одиннадцать PzKpfw III и два орудия.', '최소 1대 이상의 적을 격파하고, 5곳 이상의 부품에 치명적인 피해를 입고 전차 내구도의 80% 이상에 해당하는 피해를 받은 상태로 생존하여 해당 전투에서 승리한 자에게 수여.\n클랜전에서는 수여되지 않는다.\n\n프랑스 육군의 피에르 비요트 대위는 1940년 5월 16일 Char B1 bis 전차로 2대의 PzKpfw IV와 11대의 PzKpfw III, 2대의 야포를 격파했다.', 'medal_billotte'),
(770, 'medalLavrinenko', 'MAJOR', 0, 'Lavrinenko''s Medal', 'Медаль Лавриненко', '라브리넨코 훈장', 'Awarded for reducing the total number of capture points of a friendly base, up to 100 points per battle.', 'Выдаётся за суммарное количество сбитых очков захвата базы. За каждый бой в зачёт идёт не более 100 очков.', '적의 아군기지 점령 수치를 감소시킨 양의 총합에 따라 수여하며, 전투당 최대 100점까지 집계된다.', 'medal_lavrinenko'),
(200, 'medalKolobanov', 'EPIC', 1, 'Kolobanov''s Medal', 'Медаль Колобанова', '콜로바노프 훈장', 'Awarded to a player who stands alone against five or more enemy tanks or self-propelled guns and wins.\nUnavailable in Clan Wars.\n\nColonel Zinoviy Kolobanov was a Soviet tank ace who destroyed 22 German tanks, two guns, and two half-tracks with his KV-1 in battle on August 19th, 1941.', 'Награждается игрок, оставшийся в одиночестве против 5-ти и более вражеских танков или САУ и одержавший победу.\nНе выдаётся в клановых войнах.\n\nЗиновий Григорьевич Колобанов — советский танкист-ас, подполковник. В бою 19 августа 1941 г. на КВ-1 уничтожил двадцать два немецких танка, два орудия и два бронетранспортёра.', '아군이 모두 격파되고 혼자 남은 상태에서 5대 이상의 적 전차나 자주포를 상대로 승리 시 수여.\n클랜전에서는 수여되지 않는다.\n\n지노비 콜로바노프 중령은 소련의 전차 에이스로, 1941년 8월 19일 자신의 KV-1 전차를 지휘하여  22대의 독일군 전차와 2대의 자주포, 2대의 반궤도 장갑차를 격파하였다.', 'medal_kolobanov'),
(580, 'invincible', 'SPECIAL', 1, 'Invincible', '«Неуязвимый»', '천하무적', '• Survive 5 or more battles in a row without taking any damage.\n	• An unbroken series continues in the next battle on the current vehicle.\n	• Battles fought on self-propelled guns do not count.\n	• Every vehicle has its own series. Only the longest series is included.', '• Присуждается игроку, который участвовал в 5-ти и более боях подряд на одной и той же машине и не получил ни одного повреждения.\n	• Если серия не прервалась, то в зачёт пойдут также результаты следующего боя на этой же машине.\n	• Серия ведётся для каждой машины отдельно. В общий зачёт идёт максимальная серия.\n	• Бои на САУ в зачёт не идут.', '• 전투에서 5회 이상 연속으로 피해를 전혀 입지 않고 생존 시 획득.\n	• 연속으로 기록이 이어질 경우, 동일 전차를 이용한 다음 전투에도 해당 기록이 계속된다.\n	• 자주포로 진행한 전투는 집계되지 않는다.\n	• 모든 전차는 각기 기록을 가진다. 가장 높은 횟수만 기록된다.', 'invincible'),
(820, 'lumberjack', 'MEMORIAL', 1, 'Lumberjack', '«Лесоруб»', '나무꾼', '• Destroy at least 3 enemy vehicles and bring down at least 30 trees.\n	• You can get the award only if your team wins the game.', 'Присуждается игроку победившей команды, который уничтожил не менее 3-х противников, повалив при этом не менее 30 деревьев.', '• 최소 3대의 적 전차를 파괴하고 30그루의 나무를 쓰러뜨렸을 시 획득.\n	• 전투 승리 시에만 획득 가능하다.', 'lumberjack'),
(510, 'tankExpert', 'SPECIAL', 0, 'Master Tanker', '«Эксперт»', '전차의 달인', '• Destroy at least one of every type of enemy vehicle currently available in the game.\n	• In the event that new vehicles are added to any tech tree, the award becomes void.', '• Присуждается игроку, уничтожившему как минимум по одной машине, существующей на данный момент в дереве развития всех наций.\n	• При добавлении в любое дерево развития новых машин награда становится неактуальной.', '• 현재 게임 내에 있는 모든 전차를 최소 한 번 이상 격파 시 수여.\n	• 이후 새로운 전차가 추가되면 이 업적은 무효가 된다.', 'tank_expert'),
(500, 'diehard', 'SPECIAL', 1, 'Survivor', '«Живучий»', '생존자', '• Survive 20 or more battles in a row on the same vehicle.\n	• An unbroken series continues in the next battle on the current vehicle.\n	• Every vehicle has its own series. Only the longest series is included.\n	• Battles fought on self-propelled guns do not count.', '• Присуждается игроку, выжившему в 20-ти и более боях подряд на одной машине.\n	• Если серия не прервалась, то в зачёт пойдут также результаты следующего боя на этой же машине.\n	• Серия ведётся для каждой машины отдельно. В общий зачёт идёт максимальная серия.\n	• Бои на САУ в зачёт не идут.', '• 동일 전차로 전투에서 20회 이상 연속으로 생존 시 획득.\n	• 연속으로 기록이 이어질 경우, 동일 전차를 이용한 다음 전투에도 해당 기록이 계속된다.\n	• 모든 전차는 각기 기록을 가지며, 가장 높은 횟수만 기록된다.\n	• 자주포로 진행한 전투는 제외된다.', 'diehard'),
(740, 'medalKnispel', 'MAJOR', 0, 'Knispel''s Medal', 'Медаль Книспеля', '크니스펠 훈장', 'Awarded for the total amount of damage caused and received in four classes.', 'Выдаётся в одной из четырёх степеней в зависимости от суммарного количества нанесённого и полученного ущерба.', '적에게 입힌 피해량과 받은 피해량의 총합에 따라 4단계의 명예 훈장 수여.', 'medal_knispel'),
(570, 'armorPiercer', 'SPECIAL', 1, 'Master Gunner', '«Бронебойщик»', '사격의 달인', '• Score at least 5 armor-penetrating hits in a row against enemy vehicles.\n	• A series unbroken by a miss, non-penetration, or ricochet continues in the next battle using the current vehicle.\n	• Every vehicle has its own series. Only the longest series is included.', '• Присуждается игроку, попавшему по танку противника и пробившему броню 5 и более раз подряд.\n	• Если серия не прервалась непробитием, рикошетом или промахом, то в зачёт пойдут также результаты следующего боя на этой же машине.\n	• Серия ведётся для каждой машины отдельно. В общий зачёт идёт максимальная серия.', '• 전투에서 적 전차를 5번 이상 연속으로 관통 시 획득.\n	• 사격이 빗나가거나 장갑에 튕겨나지 않고 계속 관통될 경우, 동일 전차를 이용한 다음 전투에도 해당 기록이 계속된다.\n	• 모든 전차는 각기 기록을 가지며, 가장 높은 횟수만 기록된다.', 'armor_piercer'),
(250, 'heroesOfRassenay', 'EPIC', 1, 'Raseiniai Heroes'' medal', 'Медаль героев Расейняя', '라세이니의 훈장', 'Awarded to a player who destroys single-handedly at least 14 enemy vehicles.\nUnavailable in Clan Wars.\n\nIn June 1941, near the Lithuanian town of Raseiniai, roughly 20 KV tanks of the Soviet 3rd Mechanized Corps met the assault of the 6th Panzer Division, with approximately 100 vehicles. A single KV-2 tank managed to hold off the German advance for a full day while being pummeled by a variety of antitank weapons, until finally the KV-2 ran out of ammunition and was knocked out.', 'Награждается игрок, в одиночку уничтоживший не менее 14-ти машин противника.\nНе выдаётся в клановых войнах.\n\nВ июне 1941 года под литовским городом Расейняй произошло столкновение между частями немецкой 6-й танковой дивизии и танками КВ 3-го мехкорпуса. В сражении участвовали около двадцати советских и ста немецких танков. Несмотря на поддержку артиллерии и пехоты, немецкие войска понесли большие потери. Один из танков КВ сумел более чем на сутки перерезать немецкие коммуникации.', '한 전투에서 단독으로 14대 이상의 적을 격파하면 수여.\n클랜전에서는 수여되지 않는다.\n\n1941년 6월, 리투아니아의 라세이니 마을 근교에서 소련 3기계화군단 소속 KV 전차 20여 대가 독일군 6기갑사단의 전차 100여 대의 습격을 받았다. 그러나 KV-2 전차 한 대가 수많은 대전차화기의 공격을 버텨내며, 탄약이 떨어져 격파될 때까지 꼬박 하루 동안 독일군의 진격을 저지하였다.', 'heroes_of_rassenay'),
(460, 'sinai', 'SPECIAL', 1, 'The Lion of Sinai', '«Лев Синая»', '시나이 반도의 사자', 'Destroy at least 100 tanks of the IS series, and vehicles based on their chassis:\n	• IS\n	• IS-3\n	• IS-4\n	• IS-6\n	• IS-7\n	• IS-8\n	• ISU-152\n	• Object 704\n	• Object 261\n	• Object 268\n	• Object 263', 'Присуждается игроку, уничтожившему 100 и более танков ИС, а также машин на их базе:\n	• ИС\n	• ИС-3\n	• ИС-4\n	• ИС-6\n	• ИС-7\n	• ИС-8\n	• ИСУ-152\n	• Объект 704\n	• Объект 261\n	• Объект 268\n	• Объект 263', 'IS 계열 전차와 IS를 기반으로 한 전차 100대 이상을 격파한 자에게 수여:\n	• IS\n	• IS-3\n	• IS-4\n	• IS-6\n	• IS-7\n	• IS-8\n	• ISU-152\n	• Object 704\n	• Object 261\n	• Object 268\n	• Object 263', 'sinai'),
(520, 'tankExperts_usa', 'SPECIAL', 0, 'Expert: U.S.A.', '«Эксперт» США', '전문가: 미국', '• Destroy at least one vehicle of each type from the U.S. tech tree.\n	• The total of "Experts" can equal the number of nations in the game.\n	• In the event that new vehicles are added to the tech tree, the award becomes void.\n\nPlease check the Achievements section of the game for the award current status.', '• Присуждается игроку, уничтожившему как минимум по одной машине, существующей на данный момент в дереве развития США.\n	• Экспертов по нации может быть столько, сколько наций в игре.\n	• При добавлении в дерево развития новых машин награда становится неактуальной.\n\nПожалуйста, проверяйте текущий статус награды в разделе игрового клиента "Достижения".', '• 미국 국적의 모든 차량을 최소 한 대 이상 격파 시 수여.\n	• "전문가" 수여 횟수는 게임 내 등장 국가의 수와 같다.\n	• 이후 미국 국적의 새로운 전차가 추가되면 이 업적은 무효가 된다.\n\n보상에 대한 현재 상태를 보시려면 게임 내 업적 부분을 확인해 주십시오.', 'tank_experts_usa'),
(530, 'mechanicEngineers_usa', 'SPECIAL', 0, 'Technical Engineer, U.S.A.', '«Инженер-механик» США', '미국 전차 개발자', '• Research all vehicles in the U.S. tech tree.\n	• In the event that new vehicles are added to the tech tree, the award becomes void.\n\nPlease check the Achievements section of the game for the award current status.', '• Присуждается игроку, который исследовал всю технику, существующую на данный момент в дереве развития США.\n	• При добавлении в дерево развития новых машин награда становится неактуальной.\n\nПожалуйста, проверяйте текущий статус награды в разделе игрового клиента "Достижения".', '• 미국의 모든 전차 연구 완료.\n	• 연구 가능한 새로운 전차가 추가되면, 해당 업적은 무효가 된다.\n\n보상에 대한 현재 상태를 보시려면 게임 내 업적 부분을 확인해 주십시오.', 'mechanic_engineers_usa'),
(540, 'mechanicEngineer', 'SPECIAL', 0, 'Senior Technical Engineer', 'Старший инженер-механик', '수석 전차 개발자', '• Research all vehicles in all tech trees.\n	• In the event that new vehicles are added to the tech trees, the award becomes void.', '• Присуждается игроку, который исследовал всю технику, существующую на данный момент в дереве развития всех наций.\n	• При добавлении в дерево развития новых машин награда становится неактуальной.', '• 모든 전차 연구 완료.\n	• 연구 가능한 새로운 전차가 추가되면, 해당 업적은 무효가 된다.', 'mechanic_engineer'),
(70, 'evileye', 'BATTLE', 1, 'Patrol Duty', '«Дозорный»', '정찰 임무', '• Help your team damage at least 6 enemy vehicles by highlighting them.\n	• If two or more players have equal amount of enemy vehicles highlighted and destroyed, or if two or more players highlight the same vehicle, the achievement is granted to the player who has earned more XP in the battle.', '• Присуждается игроку, по разведданным которого членами его команды было повреждено не менее 6-ти танков противника.\n	• При равном количестве повреждённых танков, а также при получении разведданных от разных игроков, приоритет у того, кто получил больше очков опыта.', '• 발견한 적 전차 중 최소 6대를 아군이 피해를 주도록 도왔을 시 획득.\n	• 2명 이상의 플레이어가 동일한 숫자의 적 전차를 발견하여 파괴하도록 도움을 주었다면, 해당 전투에서 더 많은 경험치를 획득한 플레이어가 획득한다.', 'evileye'),
(260, 'medalBrunoPietro', 'EPIC', 1, 'Bruno''s medal', 'Медаль Бруно', '브루노 훈장', 'Awarded to players who destroy 3 or 4 enemy vehicles and survive the battle to victory despite receiving 5 different critical hits and losing 90% of their hit points.\nUnavailable in Clan Wars.\n\nPietro Bruno was an Italian tank ace. For exceptional valor in the face of the enemy he was awarded the Gold Medal of Military Valor (Medaglia d''oro al Valore Militare), the highest Italian award.', 'Награждается игрок, уничтоживший 3 или 4 машины противника в победном бою.\nДля получения награды необходимо выжить, несмотря на получение 5-ти разных критических повреждений и потерю 90% прочности танка.\nНе выдаётся в клановых войнах.\n\nПьетро Бруно — итальянский офицер, танкист. Кавалер высшей награды Италии за подвиг на поле боя — золотой медали «За воинскую доблесть».', '3~4대의 적을 격파하고 5곳의 이상의 부품에 치명적인 피해를 입고 전차 내구력의 90%에 해당하는 피해를 받은 상태로 살아남아 해당 전투에서 승리한 자에게 수여.\n클랜전에서는 불가능\n\n피에로 브루노는 이탈리아 전차 격파왕으로 적군 앞에서 뛰어난 용맹을 펼쳤다. 이탈리아 최고 훈장인 군 무공 금장(Medaglia d''oro al Valore Militare)을 수여 받았다.', 'medal_bruno_pietro'),
(270, 'medalTarczay', 'EPIC', 1, 'Tarczay''s medal', 'Медаль Тарцая', '타르차이 훈장', 'Awarded to players who destroy 5 enemy vehicles and survive the battle to victory despite receiving five different critical hits and losing 80% or more of their hit points.\nDestroyed enemy vehicles count after all damage is received.\nUnavailable in Clan Wars.\n\nErvin Tarczay was a Hungarian tank ace. He fought with the Hungarian 2nd Armored Division and destroyed at least ten enemy vehicles.', 'Награждается игрок, уничтоживший не менее 5 машин противника в победном бою.\nДля получения награды необходимо выжить, несмотря на получение 5-ти разных критических повреждений и потерю 80% прочности танка.\nУчёт уничтоженных противников начинается после получения всех перечисленных повреждений.\nНе выдаётся в клановых войнах.\n\nЭрвин Тарцай — венгерский танковый ас. Служил во 2-й венгерской танковой дивизии, уничтожил около десяти танков.', '5대의 적을 격파하고 5곳의 부품에 치명적인 피해를 입고 전차 내구도의 80% 이상의 피해를 받은 상태로 살아남아 해당 전투에서 승리한 자에게 수여.\n클랜전에서는 수여되지 않는다.\n\n에르빈 타르차이는 헝가리의 전차 에이스로 헝가리군 2기갑사단에서 복무하며 최소 10대 이상의 적 차량을 격파하였다.', 'medal_tarczay');
INSERT INTO `cat_achiev_details` (`id`, `name`, `type`, `needLabel`, `title_en`, `title_ru`, `title_ko`, `description_en`, `description_ru`, `description_ko`, `icon`) VALUES
(280, 'medalRadleyWalters', 'EPIC', 1, 'Radley-Walters''s medal', 'Медаль Рэдли-Уолтерса', '래들리-월터스 훈장', 'Awarded to players on vehicles of the 5th or higher tier for destroying 8 or 9 enemy vehicles in one battle.\nThe medal is not awarded in Clan Wars.\n\nSydney Valpy Radley-Walters was a Canadian tank ace of the 27th Armored Regiment. In 1944–1945 he destroyed 18 German vehicles with his Sherman Firefly.', 'Награждается игрок на технике 5-го уровня и выше, уничтоживший в одном бою 8 или 9 машин противника.\nНе выдаётся в клановых войнах.\n\nСидней Валпи Рэдли Уолтерс — канадский танковый ас 27-ого танкового полка. На танке Sherman Firefly уничтожил восемнадцать немецких танков в 1944–1945 гг.', '한 전투에 8~9대의 적 전차나 자주포 격파 시 수여. 적 전차는 5단계 이상 높아야 한다.\n클랜전에서는 수여되지 않는다.\n\n시드니 벌피 래들리-월터스는 캐나다군 27기갑연대의 전차 에이스로, 1944년부터 1945년까지 Sherman Firefly로 독일군 차량 18대를 격파하였다.', 'medal_radley_walters'),
(290, 'medalLafayettePool', 'EPIC', 1, 'Pool''s medal', 'Медаль Пула', '풀 훈장', 'Awarded to players on vehicles of the 5th or higher tier for destroying 10–13 enemy vehicles in one battle.\nUnavailable in Clan Wars.\n\nLafayette G. Pool is widely recognized as the U.S. tank ace of aces, credited with 12 confirmed tank kills and 258 total armored vehicle and self-propelled gun kills.', 'Награждается игрок на технике 5-го уровня и выше, уничтоживший в одном бою 10–13 машин противника.\nНе выдаётся в клановых войнах.\n\nЛафайет Дж. Пул — американский танковый ас. За время участия в боевых действиях подбил и уничтожил 258 немецких бронемашин и автомобилей.', '한 전투에서 10~13대의 전차 혹은 자주포를 격파하면 수여. 적 차량은 5단계 이상이어야 한다.\n클랜전에서는 수여되지 않는다.\n\n라파예트 G. 풀은 미국 최고의 전차 에이스로 널리 인정받고 있으며, 전차 12대의 공인 격파기록을 포함하여 총 258대의 장갑차량과 자주포를 격파하였다.', 'medal_lafayette_pool'),
(300, 'medalPascucci', 'EPIC', 1, 'Pascucci''s medal', 'Медаль Паскуччи', '파스쿠치 훈장', 'Awarded for destroying 3 enemy SPGs in one battle, with a tank or tank destroyer.\nUnavailable in Clan Wars.\n\nSecond Lieutenant Luigi Arbib Pascucci was an Italian tank commander during World War Two. He fought with the Ariete Tank Division in North Africa. Pascucci fought in the Second Battle of El Alamein, where he sacrificed his life in a reckless frontal attack that enabled the rest of his company escape encirclment.', 'Награждается игрок, уничтоживший на танке или ПТ-САУ в одном бою 3 САУ противника.\nНе выдаётся в клановых войнах.\n\nЛуиджи Арбиб Паскуччи — итальянский танковый ас. Командир 10-го танкового взвода 132-го танкового полка 132-й танковой дивизии Ariete. Во время второго сражения при Эль-Аламейне возглавил контратаку, в результате которой британские войска понесли существенные потери.', '전차나 구축전차로 한 전투 동안 3대의 적 자주포 격파 시 수여.\n클랜전에서는 수여되지 않는다.\n\n루이기 아르비브 파스쿠치 소위는 2차 대전 당시의 이탈리아군 전차장으로 북아프리카의 아리에테 전차사단에서 복무하였다. 그는 2차 엘 알라메인 전투 당시 육탄공격으로 포위망을 돌파하여 자신이 지휘하던 중대원들을 탈출시키고 장렬히 전사하였다.', 'medal_pascucci'),
(310, 'medalDumitru', 'EPIC', 1, 'Dumitru''s medal', 'Медаль Думитру', '두미트루 훈장', 'Awarded for destroying 4 enemy SPGs in one battle, with a tank or tank destroyer.\nUnavailable in Clan Wars.\n\nIon S. Dumitru was a Romanian tank ace. He fought in World War II for just twenty-five days, of which five on the German side, and, after Romania changed sides, twenty days against the Germans. On March 6th, 1945, Dumitru contributed to the destruction of six enemy tank destroyers and capture of a battery of 150 mm guns.', 'Награждается игрок, уничтоживший на танке или ПТ-САУ в одном бою 4 САУ противника.\nНе выдаётся в клановых войнах.\n\nИон С. Думитру — румынский танковый ас. Участвовал во Второй мировой войне в течение всего двадцати пяти дней. Из них пять дней он воевал на стороне Германии и двадцать — в составе советской 27-й танковой бригады. 6 марта 1945 г. подразделение, в составе которого был Думитру, уничтожило шесть немецких противотанковых орудий и захватило батарею 15-см гаубиц.', '전차 혹은 구축전차로 한 전투에서 적 자주포 4대를 격파 시 수여.\n클랜전에서는 수여되지 않는다.\n\n이온 S. 두미트루는 루마니아의 전차 에이스이다. 그가 2차 세계 대전에 참전한 기간은 모두 합쳐 단 25일에 불과했으며, 이 중 5일은 독일 편에서, 이후 루마니아가 연합국으로 돌아서게 되면서 나머지 20일은 소련 편에서 싸웠다. 1945년 3월 6일, 드미트루는 적 구축전차 6대를 격파하고 150mm 포대를 점령하는 공을 세웠다.', 'medal_dumitru'),
(320, 'medalLehvaslaiho', 'EPIC', 1, 'Lehväslaiho''s medal', 'Медаль Лехвеслайхо', '레배슬라이호 훈장', 'Awarded to players on medium tanks who destroy 2 enemy tanks or tank destroyers. The enemy vehicles must be at least 2 tiers higher.\nUnavailable in Clan Wars.\n\nReino Lehväslaiho was a Finnish tank ace who destroyed seven tanks and tank destroyers.', 'Награждается игрок, в ходе боя на среднем танке уничтоживший 2 танка или ПТ-САУ противника. В зачёт идут цели, превосходящие танк игрока не менее, чем на 2 уровня.\nНе выдаётся в клановых войнах.\n\nРейно Лехвеслайхо — сержант танковой бригады финской танковой дивизии. Подбил семь танков и ПТ-САУ.', '중(中)형전차로 2대 이상의 적 전차 격파 시 수여. 적 전차는 최소한 2단계 이상 높아야 한다.\n클랜전에서는 수여되지 않는다.\n\n레이노 레배슬라이호는 핀란드의 전차 에이스로, 7대의 전차와 구축전차를 격파했다.', 'medal_lehvaslaiho'),
(330, 'medalNikolas', 'EPIC', 1, 'Nicols''s medal', 'Медаль Николса', '니콜스 훈장', 'Awarded to players on medium tanks who destroy at least 4 enemy tanks or tank destroyers. The enemy vehicles must be at least 2 tiers higher.\nUnavailable in Clan Wars.\n\nAlfie Nicols was a British tank gunner. During the battle of Al Alamein he destroyed fourteen enemy vehicles.', 'Награждается игрок, в ходе боя на среднем танке уничтоживший не менее 4-х танков или ПТ-САУ противника. В зачёт идут цели, превосходящие танк игрока не менее, чем на 2 уровня.\nНе выдаётся в клановых войнах.\n\nЭлфи Николс — английский танковый снайпер. За один день битвы при Эль-Аламейне уничтожил девять немецких танков. Всего в ходе битвы подбил четырнадцать танков противника.', '중(中)형전차로 최소 4대 이상의 적 전차를 격파 시 수여. 적 전차는 최소 2단계 이상 높아야 한다.\n클랜전에서는 수여되지 않는다.\n\n알피 니콜스는 영국 전차 장전수이며, 알 알라메인 전투 중에 14대의 적 전차를 격파했다.', 'medal_nikolas'),
(340, 'medalTamadaYoshio', 'EPIC', 1, 'Tamada Yoshio medal', 'Медаль Тамада Йошио', '타마다 요시오 훈장', 'Awarded to a player on a light tank who in the course of one battle destroys 3 enemy self-propelled guns. Destroyed enemy vehicles must be at least 2 tiers higher than the player''s tank. To receive the award, you must survive.', 'Награждается игрок на лёгком танке, уничтоживший в одном бою 3 САУ противника. Уничтоженная техника должна превосходить танк игрока как минимум на 2 уровня. Для получения награды необходимо выжить.', '경전차로 적 자주포를 3대 이상 격파 시 수여. 파괴한 적 자주포는 플레이어보다 최소 2단계 이상 높아야 한다. 훈장을 얻기 위해서는 생존해야 한다.', 'medal_tamada_yoshio'),
(350, 'medalDeLanglade', 'EPIC', 1, 'De Langlade''s medal', 'Медаль де Ланглада', '드 랑글라드 훈장', 'Awarded to a player who in the course of one battle destroys 4 enemy vehicles within a base circle while they are attempting to capture the base. Enemy vehicles may attempt to capture the base all at once or in turn.\n			\n			Paul Girot de Langlade was a French Army lieutenant-colonel during WWII. In September 1943 he was promoted to colonel. De Langlade fought with the 2nd Tank Division under General Leclerc. On September 12–13, 1944, a combat team under de Langlade''s command wiped out Panzerbrigade 112 in the battle of Dompaire, France. Only 4 vehicles out of 45 Panthers survived the battle.', 'Награждается игрок, уничтоживший в одном бою в кругу захвата базы 4 машины противника, захватывающие базу. Захват может быть как последовательным, так и одновременным.\n			\n			Поль де Ланглад — во время Второй мировой войны подполковник, а с сентября 1943 года полковник французской армии, воевал в составе 2-ой бронетанковой дивизии генерала Леклерка. В бою у г. Домпэр (Франция) 12–13 сентября 1944 года боевая тактическая группа под командованием де Ланглада почти полностью уничтожила 112-ую панцербригаду. После боя из 45-ти «Пантер» осталось всего 4 танка.', '전투 중 기지를 점령 중인 적 전차를 4대 이상 파괴한 플레이어에게 수여. 적 전차는 동시 또는 번갈아가며 점령을 시도할 수도 있다.', 'medal_de_langlade'),
(590, 'bombardier', 'SPECIAL', 1, 'Bombardier', '«Бомбардир»', '포격수', '• Destroy at least 2 enemy vehicles with one shell.\n	• Series on all vehicles are summed up.', '• Присуждается игроку, уничтожившему одним снарядом не менее 2-х машин противника.\n	• В общий зачёт идёт сумма результатов по всем машинам.', '• 포탄 한 개로 최소 2대의 적 전차 격파 시 획득.\n	• 모든 전차의 기록이 누적됨.', 'bombardier'),
(600, 'medalBrothersInArms', 'SPECIAL', 1, 'Brothers in Arms', '«Братья по оружию»', '전우애', '• Each platoon member must destroy at least 3 enemy vehicles and survive.\n	• All platoon members receive the award.', '• Для получения награды каждый игрок взвода должен уничтожить не менее 3-х машин противника и выжить.\n	• Присуждается всем игрокам взвода.', '• 각 소대원은 각기 3대 이상의 적 전차를 파괴하고 생존해야 함.\n	• 소대원 모두 업적 획득.', 'medal_brothers_in_arms'),
(610, 'medalCrucialContribution', 'SPECIAL', 1, 'Crucial Contribution', '«Решающий вклад»', '최고 공헌자', '• Platoon must destroy at least 12 enemy vehicles.\n	• All platoon members receive the award.', '• Для получения награды взводу необходимо уничтожить не менее 12-ти машин противника.\n	• Присуждается всем игрокам взвода.', '• 소대는 최소 12대의 적 전차를 파괴하여야 함.\n	• 소대원 모두 업적 획득.', 'medal_crucial_contribution'),
(591, 'pattonValley', 'SPECIAL', 1, 'Valley of Pattons', '«Долина Паттонов»', '패튼의 골짜기', 'Destroy 100 Patton tanks:\n	• M46 Patton\n	• M48A1 Patton III', 'Присуждается игроку, уничтожившему 100 танков Patton:\n	• M46 Patton\n	• M48A1 Patton III', 'Patton 전차를 100대 격파한 자에게 수여:\n	• M46 Patton\n	• M48A1 Patton III', 'patton_valley'),
(790, 'luckyDevil', 'MEMORIAL', 1, 'Lucky', '«Счастливчик»', '행운아', '• Witness an enemy vehicle being shot and destroyed by another enemy team player.\n	• You must be 10 meters or less from the enemy vehicle at the moment of its destruction.\n	• Unavailable in Clan Wars.', '• Присуждается игроку, который находился на расстоянии не более 10 метров от танка противника в момент его уничтожения выстрелом игрока вражеской команды.\n	• Не выдаётся в клановых войнах.', '• 적 전차가 적군에게 파괴되는 것을 목격 시 획득.\n	• 적 전차가 파괴될 때 최대 10미터 이내 거리에 있어야 한다.\n	• 클랜전에서는 수여받을 수 없다.', 'lucky_devil'),
(800, 'ironMan', 'MEMORIAL', 1, 'Cool-Headed', '«Невозмутимый»', '냉철함', '• Survive at least 10 ricochets and non-penetrations in a row from enemy team players.\n	• Unavailable in Clan Wars.', '• Присуждается игроку, который получил подряд 10 и более рикошетов и непробитий от игроков вражеской команды.\n	• Не выдаётся в клановых войнах.', '• 적군으로부터 연속해서 최소 10발의 관통탄을 튕겨내거나 고폭탄을 맞고도 생존 시 획득.\n	• 클랜전에서는 수여되지 않는다.', 'iron_man'),
(810, 'sturdy', 'MEMORIAL', 1, 'Spartan', '«Спартанец»', '스파르타인', '• Survive a ricochet or non-penetration from an enemy team player.\n	• Your vehicle must have less than 10% of its hit points left.\n	• Unavailable in Clan Wars.', '• Присуждается игроку, получившему рикошет или непробитие от игрока команды противника при прочности танка меньше 10 процентов.\n	• Для получения награды необходимо выжить.\n	• Не выдаётся в клановых войнах.', '• 관통탄이나 고폭탄에 맞고 생존 시 수여.\n	• 남은 내구도가 전체 내구도의 10% 미만이여야 획득 가능하다.\n	• 클랜전에서는 수여받을 수 없다.', 'sturdy'),
(830, 'alaric', 'MEMORIAL', 1, 'Alaric', '«Аларих»', '알라릭', '• Destroy at least 2 enemy vehicles and demolish at least one monument.\n	• You can get the award only if your team wins the game.', 'Присуждается игроку победившей команды, который уничтожил не менее 2-х противников, разрушив при этом хотя бы один памятник.', '• 최소 2대의 적 전차를 격파하고 최소 1개의 기념비 파괴 시 획득.\n	• 전투 승리 시에만 획득 가능하다.', 'alaric'),
(840, 'huntsman', 'MEMORIAL', 1, 'Ranger', '«Егерь»', '특전대', '• Destroy all enemy light tanks (at least 3) in the course of one battle.\n	• Unavailable in Clan Wars.', '• Присуждается за уничтожение в одном бою всех лёгких танков противника (не менее 3-х).\n	• Не выдаётся в клановых войнах.', '• 한 전투에서 모든 적 경전차를 최소 3대 파괴 시 획득.\n	• 클랜전에서는 수여되지 않는다.', 'huntsman');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
